image: registry.gitlab.com/imperva-community/public/docker/cibuilder:stable

services:
- docker:dind

stages:
- build

build:
  stage: build
  except:
  - tags
  script:
  - build.sh "imperva-web-api-composer"
