version: "3"

services:
  imperva-web-api-composer:
    image: gsateam/imperva-web-api-composer:latest
    ports:
      - 8080:80
      - 8443:443
    environment:
      TZ: ${TZ:-UTC}
      CONTAINER_NAME: imperva-web-api-composer

